---
- hosts: all
  become: yes
  tasks:
  - name: install tree
    apt:
     name: tree
     state: present
  - name: install wget
    apt:
     name: wget
     state: present
  - name: install websrver
    apt:
     name: apache2
     state: present